[package]
name = "chat_room"
version = "1.0.0"
authors = []

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
chat_room = "d50d955258a24a801cea515ca94d58890852eba3d45796cce14819c2845f1b7e"

[dev-addresses]
